image: node:alpine

pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
  variables:
    PUBLIC_URL: "/todo-part-3" # slash is important


